### ISSUE TITLE
Ambiguous method call, when called from JAVA

### ISSUE THREAD

**Issue by dzboot02** [DavidBarbaran/FCM-AndroidToOtherDevice#2]
```
Notification notification = new Notification(title.getText().toString(), message.getText().toString());

      FirebasePush pushBuilder = new FirebasePush("api key");
      pushBuilder.setNotification(notification)
                 .setAsyncResponse(new PushNotificationTask.AsyncResponse() {

                    @Override
                    public void onFinishPush(@NotNull String s) {

                    }
                 });

      pushBuilder.sendToTopic("all");
```

`setNotification()` is causing :

> Ambiguous method call, both setNotification(Notification) in FirebasePush and setNotification(Notification) in FirebasePush match.

**Comment by DavidBarbaran** [comment]
Hello @hiddeneyes02 thanks for reporting this error.
I have fixed this error in this version of the library:

`implementation 'com.github.DavidBarbaran:FCM-AndroidToOtherDevice:1.1.1RC-SNAPSHOT'`

could you help me by confirming if this solution works, I tested it on my devices and it worked.

**Comment by DavidBarbaran** [comment]
Hello @hiddeneyes02 thanks for reporting this error.
I have fixed this error in this version of the library:

`implementation 'com.github.DavidBarbaran:FCM-AndroidToOtherDevice:1.1.1RC-SNAPSHOT'`

could you help me by confirming if this solution works, I tested it on my devices and it worked.

**Comment by DavidBarbaran** [comment]
Hello @hiddeneyes02 thanks for reporting this issue.
I have fixed this error in this version of the library:

`implementation 'com.github.DavidBarbaran:FCM-AndroidToOtherDevice:1.1.1RC-SNAPSHOT'`

could you help me by confirming if this solution works, I tested it on my devices and it worked.

**Comment by dzboot02** [comment]
All good now, thank you :)
