### ISSUE TITLE
i have one proplem

### ISSUE THREAD

**Issue by su0ltan** [DavidBarbaran/FCM-AndroidToOtherDevice#4]
i can't decide the importance of notify High or low you know? can u add it?

**Comment by DavidBarbaran** [comment]
Hello @su0ltan the importance of the notification is decided at the time of the construction of the notification channel, not in the notification, for example:

```
val importance = NotificationManager.IMPORTANCE_HIGH
val mChannel = NotificationChannel(channelId, channelName, importance)
notificationManager.createNotificationChannel(mChannel)
```

What you could do is send extra data:

```
val yourExtraData = JSONObject().put("importance", "high")  
  
val firebasePush = FirebasePush.build("LEGACY_SERVER_KEY")  
        .setNotification(notification)  
        .setData(yourExtraData)  
        .setOnFinishPush { onFinishPush() } 
``` 

And in your messaging service, which is where you receive the notification, you can read the value that you send through the key and make the logic of whether the notification is important or not.
 
I hope I've helped :D

**Comment by su0ltan** [comment]
Thank you sir David you help a lot ;D

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
