### ISSUE TITLE
Legacy server key is missing

### ISSUE THREAD

**Issue by yhayaks** [DavidBarbaran/FCM-AndroidToOtherDevice#5]
Legacy server key is missing in firebase now

**Comment by DavidBarbaran** [comment]
Hello @yhayaks sorry for replying after a long time

Now use the server key in the Cloud Messaging tab in your project settings in firebase.

**Comment by DavidBarbaran** [comment]
I have updated the Readme and Wiki file.
I hope I've helped!

https://github.com/DavidBarbaran/FCM-AndroidToOtherDevice/wiki/How-to-get-the-firebase-server-key
